version: '3.7'

services:
  app:
    build: .
    image: ig5_web
    command: tail -f /dev/null
    volumes:
      - .:/code
      - web_vscode_server:/root/.vscode-server/
    ports:
      - 5000:8000

volumes:
  web_vscode_server:
